import { Pokemon } from "../model/pokemon";

export const POKEMONS: Pokemon[] = [
  {
    id: 1,
    name: "Bulbizarre",
    hp: 25,
    cp: 5,
    picture: "assets/images/001.png",
    type: "Plante",
    createdAt: new Date(),
  },
  {
    id: 2,
    name: "Salamèche",
    hp: 28,
    cp: 6,
    picture: "assets/images/004.png",
    type: "Feu",
    createdAt: new Date(),
  },
  {
    id: 3,
    name: "Carapuce",
    hp: 21,
    cp: 4,
    picture: "assets/images/007.png",
    type: "Eau",
    createdAt: new Date(),
  },
  {
    id: 4,
    name: "Aspicot",
    hp: 16,
    cp: 2,
    picture: "assets/images/013.png",
    type: "Insecte",
    createdAt: new Date(),
  },
  {
    id: 5,
    name: "Roucool",
    hp: 30,
    cp: 7,
    picture: "assets/images/016.png",
    type: "Vol",
    createdAt: new Date(),
  },
  {
    id: 6,
    name: "Rattata",
    hp: 18,
    cp: 6,
    picture: "assets/images/019.png",
    type: "Normal",
    createdAt: new Date(),
  },
  {
    id: 7,
    name: "Piafabec",
    hp: 14,
    cp: 5,
    picture: "assets/images/021.png",
    type: "Vol",
    createdAt: new Date(),
  },
  {
    id: 8,
    name: "Abo",
    hp: 16,
    cp: 4,
    picture: "assets/images/023.png",
    type: "Poison",
    createdAt: new Date(),
  },
  {
    id: 9,
    name: "Pikachu",
    hp: 21,
    cp: 7,
    picture: "assets/images/025.png",
    type: "Electrique",
    createdAt: new Date(),
  },
  {
    id: 10,
    name: "Sabelette",
    hp: 19,
    cp: 3,
    picture: "assets/images/027.png",
    type: "Sol",
    createdAt: new Date(),
  },
  {
    id: 11,
    name: "Mélofée",
    hp: 25,
    cp: 5,
    picture: "assets/images/035.png",
    type: "Fée",
    createdAt: new Date(),
  },
  {
    id: 12,
    name: "Goupix",
    hp: 17,
    cp: 8,
    picture: "assets/images/037.png",
    type: "Feu",
    createdAt: new Date(),
  },
];
